---
title: "Milestone 1: Project Proposal"
author:
    - Sara Manders
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    keep_md: no
urlcolor: blue
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE) #already installed
```

## Project Objective

In The Netherlands, the vaccination passport is hot topic and of high interest to governmental institutions, the HORECA and entertainment industry. Should it be implemented and if so, how to market it? This study will analyze data on tweets about the vaccination passport.

## Research Question

How do people in The Netherlands tweet about the vaccination passport?

**Sub-Questions:** (if any)

Are Dutch citizens on average in favor or against the vaccination passport, according to tweets?
Does being against the vaccination passport imply those people to be against the COVID-19 vaccination?

## Type of Question

The research question I will answer is a Descriptive question.

Replace **INSERT_ANSWER** with one of the choices below:^[These question types are borrowed from a paper by Jeff Leek and Roger Peng in their paper: "What is the question?"[-@Leek1314].
]

1. Descriptive
2. Predictive
3. Causal

Once you have made your choice, remove all text except the first sentence of this section.

## Data

Keep the choice which applies to your project:

- I have downloaded the necessary data for this project. The script to download the data is [`data/download-data.R`](data/download-data.R)^[
The instructors need to be able to run this script so be clear what libraries are needed to be installed.
]
- I have not yet downloaded the final data for this project because the event I want to study has yet to occur, but have a working R script that downloads data for an earlier time period. The script to download the data is [`data/download-data.R`](data/download-data.R)^[
The instructors need to be able to run this script.
]
  - **NOTES:** Only use this option if you are using the Twitter API, and the event you plan to study has not occurred by the proposal deadline
- I am yet to download the necessary data for this project
  - **NOTES:** Selecting this option comes with a **30% penalty** to your grade as you have not met the requirements for the proposal.

## Data Description

Provide a short (max. 7 sentences) explaining the data you will use in your project.
Where is it from?
How many rows and columns?
What are the important columns for your analysis?
Provide a citation for the data if you didn't collect it yourself.

## Analysis Workflow

My workflow will follow the following steps:

* **Step 1**. SOMETHING
  * Some details
  * More details (if needed)
* **Step 2**. SOMETHING
  * Some details
  * More details (if needed)
* ...

## Communicating Results

Explain how you plan to report your results (max. 5 sentences). 
For example, what tables and figures do you expect your report will contain.
Will the table be a regression table or something else?
Will the figure(s) be a box-plot, scatter plot, something else?

## Word Count

Number of Words: `r wordcountaddin::word_count("milestone-01.Rmd")`

## References